# Generated by Django 4.1.2 on 2022-10-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('RB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('K', 'Kicker'), ('DEF', 'Defense')], default=0, max_length=3)),
            ],
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['week']},
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(to='main_app.player'),
        ),
    ]
