# Generated by Django 4.1.2 on 2022-10-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_player_alter_record_options_team_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nfl_team',
            field=models.CharField(default='Miami Dolphins', max_length=50),
            preserve_default=False,
        ),
    ]
